# -*- coding: utf-8 -*-
"""Untitled38.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tKmVyqJ2zzWawDblq3deTd7S2DHwFD9K
"""

import pandas as pd
import sqlite3
import json

orders_df = pd.read_csv('orders.csv')

with open('users.json', 'r') as f:
    users_data = json.load(f)
users_df = pd.DataFrame(users_data)

conn = sqlite3.connect(':memory:')
with open('restaurants.sql', 'r') as f:
    sql_script = f.read()
conn.executescript(sql_script)
restaurants_df = pd.read_sql_query("SELECT * FROM restaurants", conn)


merged_df = orders_df.merge(users_df, on='user_id', how='left')

final_df = merged_df.merge(restaurants_df, on='restaurant_id', how='left', suffixes=('_order', '_master'))

final_df.to_csv('final_food_delivery_dataset.csv', index=False)
print("Final Dataset Created. Shape:", final_df.shape)


final_df['order_date'] = pd.to_datetime(final_df['order_date'], format='%d-%m-%Y')

gold_city_rev = final_df[final_df['membership'] == 'Gold'].groupby('city')['total_amount'].sum()
print(f"City with highest Gold revenue: {gold_city_rev.idxmax()}")

avg_cuisine = final_df.groupby('cuisine')['total_amount'].mean()
print(f"Cuisine with highest Avg Order Value: {avg_cuisine.idxmax()}")

user_totals = final_df.groupby('user_id')['total_amount'].sum()
print(f"Distinct users with total > 1000: {(user_totals > 1000).sum()}")

bins = [3.0, 3.5, 4.0, 4.5, 5.0]
labels = ['3.0 – 3.5', '3.6 – 4.0', '4.1 – 4.5', '4.6 – 5.0']
final_df['rating_range'] = pd.cut(final_df['rating'], bins=bins, labels=labels, include_lowest=True)
print(f"Top Revenue Rating Range: {final_df.groupby('rating_range')['total_amount'].sum().idxmax()}")

gold_pct = round((final_df['membership'] == 'Gold').sum() / len(final_df) * 100)
print(f"Percentage of Gold member orders: {gold_pct}%")

final_df['quarter'] = final_df['order_date'].dt.to_period('Q')
print(f"Highest Revenue Quarter: {final_df.groupby('quarter')['total_amount'].sum().idxmax()}")

"""# New Section"""